### PR TITLE
testing against py39

### PR DESCRIPTION
**Pull request by petrus-v**

### CODE REVIEW

**Comment by petrus-v** [comment]
I was just playing around, it seems travis is not thats ready https://travis-ci.community/t/python-3-9-0-build/10091/11

Also, I'm not really sure odoo suport py 39 ! so feel free to close it

**Comment by sbidoul** [comment]
Odoo is not tested with py 39 AFAIK but one can still build wheels with py 39 if one wants.

We can keep it and merge when Travis is ready. Thanks.

**Comment by petrus-v** [comment]
thanks for feedback

just for reference regarding odoo compatibility with py3.9: https://github.com/odoo/odoo/issues/59980

**Comment by sbidoul** [comment]
Master now tests against python 3.9 (using GitHub actions).

**Pull request closed without merging**
