### PR TITLE
Improve README with requirements and some caveats.

### PR DESCRIPTION
**Pull request by sbidoul**

### CODE REVIEW

**Comment by sbidoul** [comment]
@etherealite it simply means that wherever you read `odoo.addons` or `odoo/addons` in the setuptools-odoo documentation you need to replace it by `odoo_addons` if using Odoo 8 or 9.

I'm not sure how to express that in another way. Do you have any suggestion?

**Comment by etherealite** [comment]
How about this:

Please note that if you are packaging for Odoo versions 8 or 9, you will need to make some small changes to  your module's file structure and its accompanying namespace declarations. In this case, the top most directory in an Odoo 10 path, *odoo*, will be renamed to  *odoo_addons*, such that the path `odoo/addons/<addon_name>/__manifest__.py`  becomes `odoo_addons/<addon_name>/__manifest__.py`. Calling code outside the module will require the use of an alternate reference that reflects the directory layout of the source files in pre 10 version of odoo. Any  reference to the name a Odoo 10 style namespace `odoo.addon` will need to be replaced by `odoo_addon`, this includes import statements and the `setup(namespace_packages=['odoo', 'odoo.addons'])` setuptools keyword argument which becomes `setup(namespace_packages=['odoo', 'odoo_addons'])`

**Comment by sbidoul** [comment]
@etherealite thanks for the suggestion.

Note that the part about imports is incorrect: you do not need to change anything to your code when using addons packaged this way. so `import odoo.addons....` (or `import openerp.addons....`) works in all cases.

**Comment by sbidoul** [comment]
@etherealite here is a version that is more explicit.

**Comment by etherealite** [comment]
Aww yes! This is perfect, now I see the many of my assumptions about the meaning of the original instructions were completely wrong.

I'd say that this was a good litmus test and it passed with flying colors. Much better than my long winded and incorrect explanation.

**Comment by sbidoul** [comment]
Thanks for your valuable input.

**Comment by etherealite** [comment]
@sbidoul  Glad to be of service.

Would you mind if I contacted you directly at your email address? I've got a question that isn't appropriate for GitHub.

**Comment by sbidoul** [comment]
Sure, feel free to ask.

**Pull request merged**
