### PR TITLE
Add --odoo-version-override to get_requirements

### PR DESCRIPTION
**Pull request by ayushin**
This is handy when using collect requirements without setup.py

### CODE REVIEW

**Comment by sbidoul** [comment]
Makes sense, thanks.

**Comment by sbidoul** [comment]
@ayushin do you still have plans to finish this PR ?

**Comment by ayushin** [comment]
Yes

**Comment by ayushin** [comment]
I see you have updated the README.rst already? Thanks! Anything still required from my part @sbidoul ?

**Comment by ayushin** [comment]
Closing as already merged.

**Pull request closed without merging**
